config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  
  get 'welcome/index'

  devise_for :users, controllers: {
        sessions: 'users/sessions'
      } 
  
  resources :albums 
  resources :pics 
  resources :tests 

end

app/models/album.rb
class Album < ActiveRecord::Base
  belongs_to :user
  has_many :pics , dependent: :destroy
  validates :name, presence: true
  accepts_nested_attributes_for :pics,:reject_if => lambda { |a| a[:name].blank? }, :allow_destroy => true
end

app/models/pic.rb
class Pic < ActiveRecord::Base
  belongs_to :album
  
   has_attached_file :avatar, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/

  has_and_belongs_to_many :tags
  accepts_nested_attributes_for :tags

end

app/models/tag.rb
class Tag < ActiveRecord::Base
	has_and_belongs_to_many :pics
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :albums, dependent: :destroy
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
	def index
		
		@user = current_user
		@albums = @user.albums.page(params[:page]).per(7)
		
	end
	def new
		@album = current_user.albums.new
		@user = current_user
	    
	    @pics = @album.pics.new

	    @pics.tags.build
		

	    
		
	end
	def create 
		
		@album=current_user.albums.new(album_params)
		

		if @album.save
			
	    	redirect_to @album
		else
			render 'new'
		end
	end

	def show
		@album=Album.find(params[:id])
		session[:current_album_id] = @album.id
	end

	def edit
		@album=Album.find(params[:id])
	end

	def update
	  @album =current_user.albums.find(params[:id])
	  if @album.update(album_params)
	    redirect_to @album
	  else
	    render 'edit'
	  end
	end

	def destroy 
		@album=Album.find(params[:id])
		flash[:notice] = "album  #{@album.name}, id #{params[:id]} deleted succesfully"
		@album.destroy
		redirect_to albums_path
	end

private
    def album_params
      params.require(:album).permit(:name, :description,  pics_attributes: [:name,:avatar,tags_attributes: [:name]])
     end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
# before_action :authenticate_user!

before_filter :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:account_update) { |u| 
      u.permit(:password, :password_confirmation, :current_password) 
    }
  end

  before_action :authenticate_user!

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
	def index
		
	end
	def new
		@pic = Pic.new

	end
	def create
		@pic= Pic.new(params.require(:pic).permit(:name,:desc,:album_id, :avatar))	
		@pic.save
		redirect_to album_path(session[:current_album_id])
	end
	def show
		@pic = Pic.find(params[:id])

	end

		def destroy 
		@pic=Pic.find(params[:id])
		@pic.destroy
		redirect_to albums_path
	end
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# before_filter :configure_sign_up_params, only: [:create]
# before_filter :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.for(:sign_up) << :attribute
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.for(:account_update) << :attribute
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController

# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
   #def new
     #redirect_to @users
   #end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  		@users = current_user
  		
  end
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/albums/_form.html.erb
<%= form_for @album, :class => 'form-inline' , url: albums_path do |f| %>

  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@album.errors.count, "error") %> prohibited
        this album from being saved:
      </h2>
      <ul>
        <% @album.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name ,:class => 'sr-only' %><br>
    
      <%= f.text_field :name ,:class => 'form-control',:placeholder => 'Album name' %>
    
  </div>

   <div class="form-group">

    <%= f.label :description ,:class => 'sr-only' %><br>
    <%= f.text_area :description ,:class => 'form-control',:placeholder => 'Album name'%>
  </div>

  <div id="pic" >

      <%= f.fields_for :pics do |p|   %>
         <div class="form-group">
            <%= p.label :name , :class => 'sr-only'%>
            <%= p.text_field :name ,:class => 'form-control', :placeholder => 'Pic name'%>  
            <%= p.file_field :avatar %>         

            <%= p.fields_for :tags do |t|   %>
                <%= t.label :tag_name , :class => 'sr-only'%>
                <div class="input-group">
                  <div class="input-group-addon">#</div>
                  <%= t.text_field :name, :class => 'form-control', :placeholder => 'Tags for pic ' %>
                </div>
            <% end %>
            

        </div>
      <% end %>

  </div>
<div class="btn-group" >
<%= tag "input", { "type" => "button", "value" => "Add", "onclick"=> "add()" , "class" => "btn btn-success"} %>
<%= tag "input", { "type" => "button", "value" => "remove", "onclick"=> "remov()" , "class" => "btn btn-danger" } %>
</div>



<div>
  	<%= f.submit 'Submit', :class => 'btn btn-primary' %>
  </div>
  

<%end%>

app/views/albums/edit.html.erb
<div class="row">
  <h1>Edit album - <%= @album.name %> </h1>
  <div class="col-md-5">
    <%= render 'form' %>
  </div>
  </div>

</div>

app/views/albums/index.html.erb
<p>here all albums </p>

<div class="table-responsive">
<% if @albums.count==0 %>
	<h1>Sorry no Album to Show</h1>
<% else %>

<table class="table table-hover table-bordered">
	<tr class="bg-white">
		<th>
			<p>#</p>
		</th>
		<th>
			<p>ID</p>
		</th>
		<th>
			<p>album name</p>
		</th>
		<th>
			<p> description</p>
		</th>
		<th>
			<p>actionc </p>
		</th>
		<th>
			<p>images</p>
		</th>

	</tr>

	
	<% @albums.each do |album|%>

	<tr>
		<td >
			<%= '=>' %>
		</td>
		<td>
			<p><%= album.id %></p>
		</td>
		<td>
			<p><%= album.name %></p>
		</td>
		<td>
			<p><%= album.description %></p></p>
		</td>
		<td>
			<div class="btn-group"><%=link_to 'view',album_path(album) , :class => 'btn btn-primary'%><%=link_to 'edit',edit_album_path(album) , :class => 'btn btn-success'%> <%=link_to 'delete', album_path(album), :method => :delete , :class => 'btn btn-danger' %></div>
		</td>
		<td>
			<p><%= album.pics.count %></p>
		</td>
	</tr>
	<% end %>
</table>
<%= tag "input", { "type" => "button", "value" => "delet all", "onclick"=> "albdelt()" } %>
<% end %>
</div>

app/views/albums/new.html.erb
<div class="row">
  <h1>create new album</h1>
  <div class="col-md-5">
    <%= render 'form' %>
  </div>
  </div>

</div>

app/views/albums/show.html.erb
<p>created album</p>
<div class="table-responsive">
<table class="table table-hover table-bordered">
	<tr class="bg-white">
		<th>
			<p>name</p>
		</th>
		<th>
			<p>description</p>
		</th>
		<th>
			<p>Pics</p>
		</th>
		<th>
			<p>Actions</p>
		</th>
	</tr>
	<tr>

		<td> 
			<p>	<%= @album.name %> </p>
		</td>
		<td>	
			<p> <%= @album.description %> </p>
		</td>
		<td>
			<% @album.pics.each do |p| %>
			   <a href=" <%= pic_path(p.id)  %> "><%=image_tag p.avatar.url(:thumb) %></a>

			 <% end %>
		</td>
		<td>
			<div class="btn-group">
				<%=link_to 'view',album_path(@album) , :class => 'btn btn-primary'%>
				<%=link_to 'edit',edit_album_path(@album) , :class => 'btn btn-success'%>
				<%=link_to 'delete', album_path(@album), :method => :delete , :class => 'btn btn-danger' %>
				<%= link_to "Add pic", new_pic_path, :class => 'btn btn-primary' %>
			</div>
		</td>
	</tr>
</table>
</div>

<p>Upload pics <%= link_to "Upload", new_pic_path %> </p>

app/views/layouts/albums.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Showimg" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body id="body-bg-image">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">ShowIMG</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav top-nav-custom">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Creat Album", new_album_path %></li>
            <li><%= link_to 'Back', :back %></li>
            <li><%= link_to "Show Albums", albums_path %></li>
          </ul>
        </div>
        <div class="col-md-5 pull-right">
          <% if user_signed_in? %>
            <p class="bg-success padding-15 color-black bg-shadow">you are logged in as <%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>
          <% else %>
            <p class="bg-success padding-15 color-black bg-shadow">you are not logged in please login here 
            <%= link_to 'login', user_session_path %></br>
            <span> or sign up here </span> 
            <%= link_to 'sign up', new_user_registration_path %> </p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>

      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Showimg" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body id="body-bg-image">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Showimg</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav top-nav-custom">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Creat Album", new_album_path %></li>
            <li><%= link_to 'Back', :back %></li>
            <li><%= link_to "Show Albums", albums_path %></li>
          </ul>
        </div>
        <div class="col-md-5 pull-right">
          <% if user_signed_in? %>
            <p class="bg-success padding-15 color-black bg-shadow">you are logged in as <%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>
          <% else %>
            <p class="bg-success padding-15 color-black bg-shadow">you are not logged in please login here 
            <%= link_to 'login', user_session_path %></br>
            <span> or sign up here </span> 
            <%= link_to 'sign up', new_user_registration_path %> </p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/layouts/pics.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Showimg" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body id="body-bg-image">

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#">Showimg</a>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav top-nav-custom">
            <li><%= link_to "Home", root_path %></li>
            <li><%= link_to "Creat Album", new_album_path %></li>
            <li><%= link_to 'Back', :back %></li>
            <li><%= link_to "Show Albums", albums_path %></li>
          </ul>
        </div>
        <div class="col-md-5 pull-right">
          <% if user_signed_in? %>
            <p class="bg-success padding-15 color-black bg-shadow">you are logged in as <%= current_user.email %>
            <%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>
          <% else %>
            <p class="bg-success padding-15 color-black bg-shadow">you are not logged in please login here 
            <%= link_to 'login', user_session_path %></br>
            <span> or sign up here </span> 
            <%= link_to 'sign up', new_user_registration_path %> </p>
          <% end %>
        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div><!--/.well -->
        </div><!--/span-->
      </div><!--/row-->

      <footer>
        <p>&copy; Company 2015</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>

app/views/pics/show.html.erb
<P> <%=  @pic.avatar_file_name %></p>
<p><%=  @pic.avatar_file_size %></p>
<p><%=  @pic.avatar_content_type %></P>
<p><%=  @pic.avatar_updated_at %></p>
<p><%= image_tag @pic.avatar.url(:medium) %></P>
<p><%=  @pic.avatar_content_type %></P>
	<% if @pic.tags %>
 <% @pic.tags.each do |t| %> 
 	<p>#<%= t.name  %> </p>
 <% end %>

<% end %>



<p>create new album      <%= link_to "new", new_album_path %> </p>
<p>show all albums      <%= link_to "show", albums_path %> </p>
<p>Go Home      <%= link_to "SafeHome", root_path %> </p>
<p>Upload more pics <%= link_to "Upload", new_pic_path %> </p>

<p>you are logged in as <%= current_user.email %>
<%= link_to "Sign out", destroy_user_session_path, :method => :delete %> </p>



<p><%=link_to 'view',pic_path(@pic) %>/<%=link_to 'edit',edit_pic_path(@pic) %>/<%=link_to 'delete', pic_path(@pic), :method => :delete %></p>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<p>Welcome ShowIMG</p>

 <% if user_signed_in? %>
      <%= link_to 'edit' , edit_user_registration_path %> 
  

    
  <% else %>
  	<p>you are not logged in please login here </p>
  	<%= link_to 'login', user_session_path %>

  	<span> or sign up here </span> 

  	<%= link_to 'sign up', new_user_registration_path %>
 <% end %>